Description: >
  This template creates the security groups required for any stack or application.
  We need to provide Environment, VPC ID, CIDR Range  and port as parameters.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: 'dev'
  
  CIDR:
    Description: Provide the CIDR Range for ingress rules for security group 
    Type: String
    Default: 10.0.0.0/8
  
  Port:
    Description: Provide the Port which you want to open for ingress rule
    Type: String
    Default: 443

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose the VPC in which this security groups will be deployed.
    Default: 'vpc-0af9a1f16276204b1'

Resources:
  # This security group defines who/where is allowed to access the Application Load Balancer.
  # By default, we've opened this up to the public internet (0.0.0.0/0) but can you restrict
  # it further if you want.
  rSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Access to the load balancer that sits in front of ECS
      SecurityGroupIngress:
        # Allow access from this CIDR range to application
        - CidrIp: !Ref CIDR
          IpProtocol: '-1'
          FromPort: !Ref Port
          ToPort: !Ref Port
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-LoadBalancers

Outputs:
  SecurityGroup:
    Description: A reference to the security group for load balancers
    Value: !Ref rSecurityGroup
